Refactor the read supplier and corresponding tests
Supplier-Squad-NYU/suppliers pull request #48
Opened 2021-10-31 05:08 UTC by iriswhhh

2021-10-31 17:42 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
We don't actually use this anywhere. Might as well not have it here.

2021-10-31 17:42 UTC, zhengqixi commented on service/supplier.py
> +    def find(cls, supplier_id:int):
Please add type hint on the return value. Something like:
`def find(cls, supplier_id: int) -> 'Supplier':`
Note the `'Supplier'`...this is needed if you're going to do a self reference to the class name in a class method.

2021-10-31 17:42 UTC, zhengqixi commented on tests/factories.py
> +    """Creates fake pets that you don't have to feed"""
Copy and paste comment....

2021-10-31 17:50 UTC, iriswhhh commented on tests/factories.py
> +    """Creates fake pets that you don't have to feed"""
corrected the typo.

2021-10-31 18:04 UTC, iriswhhh commented on service/supplier.py
> +    def find(cls, supplier_id:int):
added type hint.

2021-10-31 18:09 UTC, iriswhhh commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
not a problem. Just keep it.

2021-10-31 18:10 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
No. Unused code is dead code. Linters will complain about these things for a reason. Remove it unless you're going to use it.

2021-10-31 18:15 UTC, iriswhhh commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
find_or_404 is not unused. It is tested in the test_supplier.py and test_routes.py. Professor's repo also has this method.

2021-10-31 18:19 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
Tests don't count. Otherwise you can write hundreds of useless functions, write tests for them and then claim "but they're used". That would not make sense. The professor has them because they're presumably being used in some other codepath that implements a useful functionality. You're not using them in this PR. In the real world, you don't add code to a codebase if it's not being used by the application anywhere. The point of this class is to understand these standards, not just blindly copy everything in the professor's repo without really understanding what's going on.
Like I already stated, when this function is needed, it will be added by the person who will need it for the functionality its needed for. You don't need to guess what may or may not be needed going forward.

2021-10-31 18:22 UTC, iriswhhh commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
Just follow professor's lecture and repo.

![image](https://user-images.githubusercontent.com/39836651/139596637-615da618-d9a4-486a-8c33-dc8cfeab1c91.png)
Last time, we lost points because of not following the professor's lecture.

2021-10-31 18:29 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
1. If you're seriously going to just blindly copy and paste the entire repo, then why go through the whole charade of cutting tickets, splitting these things up, and doing these PRs? You can literally copy and paste the entire repo in a single PR, then just find and replace some terms. The point of this is for you to learn something, not just copy and paste your way to an easy A.
2. We lost points largely for not following REST standards. As a matter of fact, the comment we got with regards to code was "I appreciate that you tried to write your own code.". Dead code is not REST standards. Dead code is poor coding practice.

2021-10-31 18:40 UTC, iriswhhh commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
NO! I am a new beginner who has never learned design before. Following the lecture is best way to learn and understand new knowledge. Last Homework, you insist your own design and now are refactoring it. It wastes a lot of time. BTW, Professor said "Hi @Iris Wang, actually you can just cut-n-paste and rename to match your resource. This is not a class about writing code as much as it is a class about working as an agile team."

2021-10-31 19:08 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
```
you can just cut-n-paste and rename to match your resource.
```
Which I'm now okay with, because I know now that we're not going to be losing points for plagiarism.

Even if you're going to copy and paste, you need to know what it is you're copy and pasting. We're not copying the entire repo in one go, so you're going to have to use some judgement about what pieces of code you're copying and pasting across in a single PR. I'm trying to explain to you why you do not need this particular function at this time, and why it's a bad practice in the  industry to just add extra code that you don't need to a codebase. You need to understand the reasoning here if you want to get something out of this class other than just copy and pasting stuff. This is not a hard or difficult concept to grasp, and it has nothing to do with larger architectural design.

Also, if you're copying and pasting from the lecture notes, this function isn't even there. This is in the lecture notes:
```
@classmethod
def find(cls, pet_id):
""" Finds a Pet by it's ID """
    return cls.query.get(pet_id) 

@classmethod
def find_by_category(cls, category):
""" Returns all of the Pets in a category """
    return cls.query.filter(cls.category == category)
```
On slide 102 in `04-Building-RESTful-Services`
So as it stands, I don't even know why you chose to bundle this particular function in your PR, as its evident you're not copy and pasting the slide from the lectures over.

2021-10-31 19:22 UTC, iriswhhh commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
Not blindly copy and paste. I understood the functions I wrote. Also, I can delete them if you insist. Don't want to spent time in such a small problem. If you have another arguments about following the professor' repo, we can talk about it in slack. 

Collaboration is the most important thing to work as an agile team.

Another explicit requirement in the homework 1 
"Create a models.py file to hold your model definitions of your resource",
Please rename supplier.py to models.py and make corresponding changes first.
Please pay more attention to the explicit requirement of homework.

2021-10-31 19:24 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
Lets discuss over Zoom later.

2021-10-31 21:45 UTC, HughHuang96824 commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
The purpose of test cases is to test the code you have used in your project, so if a function is used in the project, it needs to be tested. The purpose of the code is not to be used in the tests.
You can  also understand in this way:
If we will eventually deliver the product to customers, they will not run the tests; in that case, the part of the code that cannot be run in any circumstances is dead code.

2021-10-31 21:50 UTC, zhengqixi commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
At this point I don't want to waste too much more time on this. As it turns out, there is a good use case for `find_or_404`, but it should be done by the functionality that actually requires said use case, rather than in an unrelated PR. I also don't think we need both `find` and `find_or_404`, but I'll take that up with professor rofrano directly instead of doing that here.

2021-11-02 17:50 UTC, iriswhhh commented on service/supplier.py
> +    def find_or_404(cls, supplier_id:int):
deleted find_or_404. Please resolve the conflicts and merge.

2021-11-03 22:54 UTC, HughHuang96824 requested changes

2021-11-03 22:54 UTC, HughHuang96824 commented on tests/test_routes.py
> +    def _create_suppliers(self, count):
func name missing test, should be test_create_suppliers

2021-11-03 22:54 UTC, HughHuang96824 commented on tests/test_routes.py
> +        self.assertEqual(data["products"], test_supplier.products, "Products does not match")
not sure if the lengths of these lines exceed the Pylint limit. Could leave it for now and refine the code format when we submit the next hw.

2021-11-04 00:12 UTC, zhengqixi commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
Why did you comment this out?

2021-11-04 00:25 UTC, iriswhhh commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
Please see https://app.codecov.io/gh/Supplier-Squad-NYU/suppliers/compare/48/tree/service

In order to pass the coverage tests, temporarily delete this function in my PR. If you want to add it, you could add it later and see the picture. I also commented on it in your PR code. 
[image](https://user-images.githubusercontent.com/39836651/140236575-df70a4f4-e39a-4b38-9822-b7d1cdf3b0ca.png)

2021-11-04 00:31 UTC, iriswhhh commented on tests/test_routes.py
> +    def _create_suppliers(self, count):
This is a helper function. Without passing the argument 'count', it cannot be tested.

2021-11-04 00:34 UTC, zhengqixi commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
Don't think this should be preventing >95% though? The previous PR was merged with >95% so if every new line added here is tested, then it should still be above 95%?

2021-11-04 00:35 UTC, zhengqixi commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
BTW Github isn't going to send messages for PRs that have already been merged. For these kinds of things you're better off pinging directly in Slack.

2021-11-04 00:40 UTC, zhengqixi commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
In any case, I'm pretty sure removing this will actually cause our service to spit 500s. 
If you do something like call create with a user provided ID, we throw an error: https://github.com/Supplier-Squad-NYU/suppliers/blob/main/service/supplier.py#L46
This handler would catch that error, and let the user know that they provided a bad input
Otherwise, flask thinks its our fault and would turn what would otherwise be a 404 into a 500. 
I'll need to update a test case in order to catch that properly.
That being said, I'm still not sure how this function would prevent >95% if all the new code is tested?

2021-11-04 00:43 UTC, iriswhhh commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
> BTW Github isn't going to send messages for PRs that have already been merged. For these kinds of things you're better off pinging directly in Slack.

Aha! I mentioned this problem in slack yesterday and also @ you, right?

2021-11-04 00:44 UTC, iriswhhh commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
Reading the report  https://app.codecov.io/gh/Supplier-Squad-NYU/suppliers/compare/48/tree/service
All new codes are tested.

If don't delete, can you give other constructive suggestions to make changes to ensure >95%? I cannot find other options.

2021-11-04 00:49 UTC, iriswhhh commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
> That being said, I'm still not sure how this function would prevent >95% if all the new code is tested?

Please Read the report https://app.codecov.io/gh/Supplier-Squad-NYU/suppliers/compare/48/tree/service
All new codes are tested.

2021-11-04 00:59 UTC, zhengqixi commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
> > BTW Github isn't going to send messages for PRs that have already been merged. For these kinds of things you're better off pinging directly in Slack.
> 
> Aha! I mentioned this problem in slack yesterday and also @ you, right?

OH that's what you meant. Okay sorry. Might've missed it since I only saw briefly skimmed some things this morning before heading to work. In any case, I think you should be able to hit that line if you add a "name" field to this test case:
https://github.com/Supplier-Squad-NYU/suppliers/blob/main/tests/test_routes.py#L111
Can you try and let me know?
And huh....I'm not sure how codecov is doing the math here but whatever.

2021-11-04 03:04 UTC, HughHuang96824 approved these changes

2021-11-04 04:37 UTC, iriswhhh commented on service/error_handlers.py
> +# @app.errorhandler(SupplierException)
I tried it. However, it seems do not work.

 <img width="780" alt="Screen Shot 2021-11-03 at 9 22 06 PM" src="https://user-images.githubusercontent.com/39836651/140257794-ed06ebe5-bb8b-433b-8482-8b8be8c31856.png">

id needs to be None, otherwise will raise UserDefinedIdError.  So I set id = None in SupplierFactory.
https://github.com/Supplier-Squad-NYU/suppliers/pull/48/commits/3d4843e81e3fe2665f9d026b77a082c54364a81e
<img width="780" alt="Screen Shot 2021-11-03 at 9 22 06 PM" src="https://user-images.githubusercontent.com/39836651/140257617-fb78aa63-ec61-44c0-8897-117a0eb35db1.png">

UserDefinedIdError is already tested in test_suppliers.py. You can also add similar test cases and confirm UserDefinedIdError will be raised. Please do these tests in another PR.

2021-11-04 04:42 UTC, merged